apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgresSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: rabbitUn
  password: rabbitSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: auction-secret
type: Opaque
stringData:
  connString: Server=postgres-clusterip:5432;User Id=postgres;Password=postgresSecretPw;Database=auctions
  rabbitUserName: rabbitUn 
  rabbitPassword: rabbitSecretPw
